[package]
name = "whisk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
pasts = "0.8"
dl_api = "0.4"
criterion = { version = "0.3", features = ["async_futures"] }
futures = "0.3"
flume = "0.10"

[features]
default = ["std"]
std = []

[[bench]]
name = "addition"
harness = false
